export const STATUS_ADOCAO = {
  ANALISE: "ANALISE",
  CONCLUIDO: "CONCLUIDO",
  FINALIZADO: "FINALIZADO",
  CANCELADO: "CANCELADO",
  REPROVADO: "REPROVADO",
};

export const STATUS_ADOCAO_VALIDOS = Object.values(STATUS_ADOCAO);
